import CryptoKit
import Cocoa

struct Clip: Codable, Equatable {
    var id = UUID()
    var text: String          // the copied text, or a description like "Image 1280×720" for images
    var image: String?        // file name in the images folder, for image clips
    var date = Date()
    var pinned = false
    var name: String?         // set for clips in the Saved tab

    var isImage: Bool { image != nil }
}

/// Watches the clipboard and keeps the saved history.
final class ClipStore {
    static let shared = ClipStore()

    private(set) var clips: [Clip] = []   // history, newest first
    private(set) var saved: [Clip] = []   // named clips kept forever, newest first
    var onChange: (() -> Void)?

    private let fileURL: URL
    private let savedURL: URL
    let imagesDir: URL
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    /// Image conversion and file writes happen here, never on the main thread.
    private let io = DispatchQueue(label: "clips.io", qos: .utility)
    private var savePending = false

    /// Clipboard markers that password managers and other apps use for "don't record this".
    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    /// Text that looks like an API key, token or private key.
    private static let secretPatterns: [NSRegularExpression] = [
        #"github_pat_[A-Za-z0-9_]{20,}"#,
        #"\bgh[pousr]_[A-Za-z0-9]{30,}"#,
        #"\bsk-[A-Za-z0-9_-]{20,}"#,
        #"\bAKIA[0-9A-Z]{16}\b"#,
        #"\bxox[abprs]-[A-Za-z0-9-]{10,}"#,
        #"-----BEGIN [A-Z ]*PRIVATE KEY-----"#,
    ].map { try! NSRegularExpression(pattern: $0) }

    var ordered: [Clip] { clips.filter(\.pinned) + clips.filter { !$0.pinned } }

    private init() {
        let dir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Clips")
        imagesDir = dir.appendingPathComponent("images")
        try? FileManager.default.createDirectory(at: imagesDir, withIntermediateDirectories: true)
        fileURL = dir.appendingPathComponent("history.json")
        savedURL = dir.appendingPathComponent("saved.json")
        if let data = try? Data(contentsOf: fileURL), let list = try? JSONDecoder().decode([Clip].self, from: data) {
            clips = list
        }
        if let data = try? Data(contentsOf: savedURL), let list = try? JSONDecoder().decode([Clip].self, from: data) {
            saved = list
        }
    }

    func startWatching() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: true) { [weak self] _ in self?.poll() }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = pb.types ?? []
        if types.contains(where: { Self.skippedTypes.contains($0.rawValue) }) { return }
        if let app = NSWorkspace.shared.frontmostApplication?.bundleIdentifier, Settings.ignoredApps.contains(app) { return }

        // Text wins when both are present (spreadsheets and documents also attach a picture of the selection).
        if let text = pb.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            if Settings.skipSecrets && Self.looksSecret(text) { return }
            add(Clip(text: text))
        } else if Settings.saveImages, !types.contains(.fileURL) {
            // Screenshots already come as PNG; other apps usually give TIFF, which is converted in the background.
            if let png = pb.data(forType: .png) {
                saveImage(png: png, tiff: nil)
            } else if let tiff = pb.data(forType: .tiff) {
                saveImage(png: nil, tiff: tiff)
            }
        }
    }

    static func looksSecret(_ text: String) -> Bool {
        let range = NSRange(text.startIndex..., in: text)
        return secretPatterns.contains { $0.firstMatch(in: text, range: range) != nil }
    }

    // MARK: Images

    /// Stores the image as a PNG named after its contents, so copying the same image twice is one clip.
    /// The heavy work (conversion, hashing, writing) runs in the background; the clip is added when it's done.
    private func saveImage(png: Data?, tiff: Data?) {
        let dir = imagesDir
        io.async { [weak self] in
            guard let data = png ?? tiff,
                  let rep = NSBitmapImageRep(data: data),
                  let png = png ?? rep.representation(using: .png, properties: [:]) else { return }
            let name = SHA256.hash(data: png).prefix(16).map { String(format: "%02x", $0) }.joined() + ".png"
            let url = dir.appendingPathComponent(name)
            if !FileManager.default.fileExists(atPath: url.path) {
                try? png.write(to: url, options: .atomic)
            }
            let text = "Image \(rep.pixelsWide)×\(rep.pixelsHigh)"
            DispatchQueue.main.async { self?.add(Clip(text: text, image: name)) }
        }
    }

    func imageURL(_ clip: Clip) -> URL? { clip.image.map { imagesDir.appendingPathComponent($0) } }

    // MARK: Editing the history

    /// Adds a clip to the top of the history, moving it up if it is already there.
    func add(_ clip: Clip) {
        var clip = clip
        if let i = clips.firstIndex(where: { $0.text == clip.text && $0.image == clip.image }) {
            clip.pinned = clips[i].pinned
            clips.remove(at: i)
        }
        clips.insert(clip, at: 0)
        trim()
        save()
    }

    /// Puts a clip on the clipboard without recording it as a new copy.
    func copyToClipboard(_ clip: Clip) {
        let pb = NSPasteboard.general
        pb.clearContents()
        if let url = imageURL(clip), let png = try? Data(contentsOf: url) {
            pb.setData(png, forType: .png)
            if let tiff = NSImage(data: png)?.tiffRepresentation { pb.setData(tiff, forType: .tiff) }
        } else {
            pb.setString(clip.text, forType: .string)
        }
        lastChangeCount = pb.changeCount
        add(Clip(text: clip.text, image: clip.image))
    }

    func togglePin(_ clip: Clip) {
        guard let i = clips.firstIndex(where: { $0.id == clip.id }) else { return }
        clips[i].pinned.toggle()
        trim()
        save()
    }

    func delete(_ clip: Clip) {
        remove { $0.id == clip.id }
        save()
    }

    /// Removes every unpinned image clip.
    func clearImages() {
        remove { $0.isImage && !$0.pinned }
        save()
    }

    /// Copies an image clip into the chosen save folder (Downloads by default) and returns where it went.
    func exportImage(_ clip: Clip) -> URL? {
        guard let source = imageURL(clip) else { return nil }
        let folder = Settings.saveFolder
        try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let stamp = DateFormatter()
        stamp.dateFormat = "yyyy-MM-dd 'at' HH.mm.ss"
        let base = "Clip \(stamp.string(from: clip.date))"
        var target = folder.appendingPathComponent(base + ".png")
        var n = 2
        while FileManager.default.fileExists(atPath: target.path) {
            target = folder.appendingPathComponent("\(base) (\(n)).png")
            n += 1
        }
        return (try? FileManager.default.copyItem(at: source, to: target)) != nil ? target : nil
    }

    // MARK: Saved clips

    /// Saves a copy of a clip under a name. Saving the same content again just renames it.
    func saveForever(_ clip: Clip, name: String) {
        if let i = saved.firstIndex(where: { $0.text == clip.text && $0.image == clip.image }) {
            saved[i].name = name
        } else {
            saved.insert(Clip(text: clip.text, image: clip.image, name: name), at: 0)
        }
        save()
    }

    func rename(_ clip: Clip, to name: String) {
        guard let i = saved.firstIndex(where: { $0.id == clip.id }) else { return }
        saved[i].name = name
        save()
    }

    func deleteSaved(_ clip: Clip) {
        saved.removeAll { $0.id == clip.id }
        deleteUnusedImages([clip])
        save()
    }

    func clearUnpinned() {
        remove { !$0.pinned }
        save()
    }

    /// Keeps every pinned clip plus the newest `maxItems` unpinned ones.
    private func trim() {
        var unpinned = 0
        let keep = Set(clips.filter { clip in
            if clip.pinned { return true }
            unpinned += 1
            return unpinned <= Settings.maxItems
        }.map(\.id))
        remove { !keep.contains($0.id) }
    }

    /// Removes clips and deletes image files that no remaining clip uses.
    private func remove(where shouldRemove: (Clip) -> Bool) {
        let removed = clips.filter(shouldRemove)
        clips.removeAll(where: shouldRemove)
        deleteUnusedImages(removed)
    }

    /// Deletes the image files of these clips unless the history or Saved still uses them.
    private func deleteUnusedImages(_ removed: [Clip]) {
        let stillUsed = Set((clips + saved).compactMap(\.image))
        for clip in removed {
            if let name = clip.image, !stillUsed.contains(name) {
                try? FileManager.default.removeItem(at: imagesDir.appendingPathComponent(name))
            }
        }
    }

    /// Updates the UI straight away and writes to disk in the background, grouping quick bursts of changes.
    private func save() {
        onChange?()
        guard !savePending else { return }
        savePending = true
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) { [self] in
            savePending = false
            let (history, named) = (clips, saved)
            let (historyURL, namedURL) = (fileURL, savedURL)
            io.async {
                if let data = try? JSONEncoder().encode(history) { try? data.write(to: historyURL, options: .atomic) }
                if let data = try? JSONEncoder().encode(named) { try? data.write(to: namedURL, options: .atomic) }
            }
        }
    }

    /// Writes any pending changes before the app quits.
    func flush() {
        if let data = try? JSONEncoder().encode(clips) { try? data.write(to: fileURL, options: .atomic) }
        if let data = try? JSONEncoder().encode(saved) { try? data.write(to: savedURL, options: .atomic) }
    }
}
